---
- name: config web services
  host:  lamp
  tasks:
    - name: this is the {{ web_package }} package
      debug:
        msg: "Installing {{ web_peckage }}"
    - name:  this is the {{ web_service }} service
      debug:
        msg: "Starting {{ web_service }}"